git:
  depth: false

matrix:
  include:
    - name: "Merge-and-build benchmark"
      language: python
      os: linux
      python: 3.8
      script: bash .travis/run_build_benchmark.sh
      addons:
         apt:
            packages:
               - openjdk-8-jdk
               - openjfx

notifications:
  email: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/jars
